version: '3.1'
services:
  postgresql:
    image: postgres
    restart: always
    environment:
       POSTGRES_USER: user
       POSTGRES_PASSWORD: password
       POSTGRES_DB: moviesCatalogue
    volumes:
        - ./postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: moviesCatalogue
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - '3306:3306'